version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5050
      - SERVER_API_URL=http://backend:5050

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emotionaltracker
      - JWT_SECRET=mysecretkey123
      - SEED_DATABASE=false

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
